Insert into
 store.product( "name_product","price","unit")
Values ( 'strela',1.26,'piece');
Insert into
 store.product( "name_product","price","unit")
Values ( 'strela Lux',1.32,'piece');
Insert into
 store.product( "name_product","price","unit")
Values ( 'postsil',1.14,'piece');
INSERT INTO store.users(
	 address, created_at, email, password, password_hash, role, telephon, user_first_name, user_name)
	VALUES ('zp',current_date   , 'ddd@ukr.net',default , default  ,'ADMIN', 0672512541, 'maskov', 'artur');
INSERT INTO store.users(
	 address, created_at, email, password, password_hash, role, telephon, user_first_name, user_name)
	VALUES ( 'kiev',current_date , 'aaa@ukr.net',default , default  ,'CLIENT', 0672512542, 'vasyutin', 'vasya');
INSERT INTO store.users(
	 address, created_at, email, password, password_hash, role, telephon, user_first_name, user_name)
	VALUES ( 'vodyane',current_date  , 'ooo@ukr.net',default , default  ,'DIRECTOR', 0672512543, 'Timlid', 'vova');
INSERT INTO store."order"(
	 count, last_order, summ, product_id, users_id)
	VALUES ( 1000, current_date , 1260, GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,default   )RETURN_GENERATED_KEYS;
INSERT INTO store."order"(
	 count, last_order, summ, product_id, users_id)
	VALUES ( 1000, current_date , 1320, currval(pg_get_serial_sequence('store.product', 'id')), currval(pg_get_serial_sequence('store.users', 'id')));
INSERT INTO store."order"(
	 count, last_order, summ, product_id, users_id)
	VALUES ( 1000, current_date , 1140, currval(pg_get_serial_sequence('store.product', 'id')), currval(pg_get_serial_sequence('store.users', 'id')));